// Generated by Supabase CLI — do not edit manually.
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > types/database.types.ts

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          full_name: string | null
          avatar_url: string | null
          created_at: string
        }
        Insert: {
          id: string
          full_name?: string | null
          avatar_url?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          full_name?: string | null
          avatar_url?: string | null
          created_at?: string
        }
        Relationships: []
      }
      venues: {
        Row: {
          id: string
          owner_id: string
          name: string
          slug: string
          description: string | null
          address: string | null
          phone: string | null
          wifi_password: string | null
          logo_url: string | null
          cover_url: string | null
          active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          owner_id: string
          name: string
          slug: string
          description?: string | null
          address?: string | null
          phone?: string | null
          wifi_password?: string | null
          logo_url?: string | null
          cover_url?: string | null
          active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          owner_id?: string
          name?: string
          slug?: string
          description?: string | null
          address?: string | null
          phone?: string | null
          wifi_password?: string | null
          logo_url?: string | null
          cover_url?: string | null
          active?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: [{ foreignKeyName: 'venues_owner_id_fkey'; columns: ['owner_id']; referencedRelation: 'profiles'; referencedColumns: ['id'] }]
      }
      categories: {
        Row: {
          id: string
          venue_id: string
          name: string
          position: number
          visible: boolean
          created_at: string
        }
        Insert: {
          id?: string
          venue_id: string
          name: string
          position?: number
          visible?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          venue_id?: string
          name?: string
          position?: number
          visible?: boolean
          created_at?: string
        }
        Relationships: [{ foreignKeyName: 'categories_venue_id_fkey'; columns: ['venue_id']; referencedRelation: 'venues'; referencedColumns: ['id'] }]
      }
      menu_items: {
        Row: {
          id: string
          category_id: string
          name: string
          description: string | null
          price: number | null
          old_price: number | null
          image_url: string | null
          visible: boolean
          unavailable: boolean
          is_new: boolean
          is_featured: boolean
          position: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          category_id: string
          name: string
          description?: string | null
          price?: number | null
          old_price?: number | null
          image_url?: string | null
          visible?: boolean
          unavailable?: boolean
          is_new?: boolean
          is_featured?: boolean
          position?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          category_id?: string
          name?: string
          description?: string | null
          price?: number | null
          old_price?: number | null
          image_url?: string | null
          visible?: boolean
          unavailable?: boolean
          is_new?: boolean
          is_featured?: boolean
          position?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: [{ foreignKeyName: 'menu_items_category_id_fkey'; columns: ['category_id']; referencedRelation: 'categories'; referencedColumns: ['id'] }]
      }
      item_translations: {
        Row: {
          id: string
          item_id: string
          locale: string
          name: string
          description: string | null
        }
        Insert: {
          id?: string
          item_id: string
          locale: string
          name: string
          description?: string | null
        }
        Update: {
          id?: string
          item_id?: string
          locale?: string
          name?: string
          description?: string | null
        }
        Relationships: [{ foreignKeyName: 'item_translations_item_id_fkey'; columns: ['item_id']; referencedRelation: 'menu_items'; referencedColumns: ['id'] }]
      }
      staff_members: {
        Row: {
          id: string
          venue_id: string
          user_id: string | null
          email: string
          role: 'editor' | 'viewer'
          invite_token: string | null
          invited_at: string
          accepted_at: string | null
        }
        Insert: {
          id?: string
          venue_id: string
          user_id?: string | null
          email: string
          role: 'editor' | 'viewer'
          invite_token?: string | null
          invited_at?: string
          accepted_at?: string | null
        }
        Update: {
          id?: string
          venue_id?: string
          user_id?: string | null
          email?: string
          role?: 'editor' | 'viewer'
          invite_token?: string | null
          invited_at?: string
          accepted_at?: string | null
        }
        Relationships: [
          { foreignKeyName: 'staff_members_venue_id_fkey'; columns: ['venue_id']; referencedRelation: 'venues'; referencedColumns: ['id'] },
          { foreignKeyName: 'staff_members_user_id_fkey'; columns: ['user_id']; referencedRelation: 'profiles'; referencedColumns: ['id'] }
        ]
      }
      subscriptions: {
        Row: {
          id: string
          owner_id: string
          stripe_customer_id: string
          stripe_subscription_id: string | null
          plan: 'trial' | 'pro' | 'chain'
          status: string
          trial_ends_at: string | null
          current_period_end: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          owner_id: string
          stripe_customer_id: string
          stripe_subscription_id?: string | null
          plan?: 'trial' | 'pro' | 'chain'
          status?: string
          trial_ends_at?: string | null
          current_period_end?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          owner_id?: string
          stripe_customer_id?: string
          stripe_subscription_id?: string | null
          plan?: 'trial' | 'pro' | 'chain'
          status?: string
          trial_ends_at?: string | null
          current_period_end?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [{ foreignKeyName: 'subscriptions_owner_id_fkey'; columns: ['owner_id']; referencedRelation: 'profiles'; referencedColumns: ['id'] }]
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}

export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row']
export type Inserts<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert']
export type Updates<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update']
